tempdir: scratch/     # files will be deleted upon pipeline completion
resultdir: results/SSvsHeinz/   # output files that you want to keep

queries_dir: SSvsHeinz/queries/ # fasta files that you want to align (e.g. scaffolds)
refs_dir: SSvsHeinz/refs/       # fasta files that you want to use as references (e.g. chromosomes)

length_threshold: 1000     # minimum length of alignment
identity_threshold: 85.0   # minimum identity score of alignment
