tempdir: scratch/     # files will be deleted upon pipeline completion
resultdir: results/   # output files that you want to keep

queries_dir: queries/ # fasta files that you want to align (e.g. scaffolds)
refs_dir: refs/       # fasta files that you want to use as references (e.g. chromosomes)
