# filtering script of the snakemake mummer pipeline (by Bleeker group)

suppressPackageStartupMessages(library(Biostrings))
suppressPackageStartupMessages(library(argparse))


get_settings <- function(length_threshold=1000, identity_threshold=90.0, n_threshold_percentage=10.0) {
  parser <- ArgumentParser(description='Calculate percentage of aligned bases')
  parser$add_argument("-f", "--filename", metavar = "character", type = "character", help = "list of input files")
  parser$add_argument("--nfile", metavar = "character", type = "character", help = "the file generated by get_N_locations")
  parser$add_argument("--out", metavar = "character", type = "character", nargs="+", help = "list of output files")
  parser$add_argument("-l", "--length_threshold", metavar = "integer", type = "integer", default =  length_threshold, help = "threshold value for length filter [default]")
  parser$add_argument("-i", "--identity_threshold", metavar = "double", type = "double", default = identity_threshold, help = "threshold value for identity filter [default]")
  parser$add_argument("--n_threshold_perc", metavar = "double", type = "double", default = n_threshold_percentage, help = "threshold value for maximum percentage of N in alignment [default]")
  settings <- parser$parse_args()
  return(settings)
}

settings = get_settings(1000, 90.0, 10.0)

# Load functions
source("scripts/aligned_perc_calc_functions.r")

# filter the alignments based on length and identity
filtered_data <- get_filtered_data(filename = settings$filename,
                                   length_threshold = settings$length_threshold,
                                   identity_threshold = settings$identity_threshold)

# filter the alignments based on percentage of n nucleotides
filter_N_entries(data = filtered_data, N_file = settings$nfile, N_threshold_perc = settings$n_threshold_perc, mode = 0, outname = settings$out)
